# Generated by Django 5.1.4 on 2025-01-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="general",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("dialCode", models.CharField(max_length=5)),
                ("image", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("contact", models.IntegerField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=250)),
                ("companyName", models.CharField(max_length=50)),
                ("gstin", models.CharField(max_length=15)),
                ("storeName", models.CharField(max_length=50)),
            ],
        ),
    ]
