# Generated by Django 5.1.4 on 2025-01-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0002_alter_seller_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="general",
        ),
    ]
