# Generated by Django 5.1.4 on 2025-01-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0003_delete_general"),
    ]

    operations = [
        migrations.CreateModel(
            name="general",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("dialCode", models.CharField(max_length=5)),
                ("image", models.CharField(max_length=100)),
            ],
        ),
    ]
