# Generated by Django 5.1.4 on 2025-01-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0004_general"),
    ]

    operations = [
        migrations.DeleteModel(
            name="general",
        ),
        migrations.AddField(
            model_name="seller",
            name="sellerID",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
