# Generated by Django 5.1.4 on 2025-01-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0005_delete_general_seller_sellerid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="sellerID",
        ),
    ]
