# Generated by Django 5.1.4 on 2025-01-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0006_remove_seller_sellerid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="contact",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="userName",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
