# Generated by Django 5.1.4 on 2025-01-09 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0007_alter_seller_contact_alter_seller_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="createOn",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seller",
            name="lastLogin",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
