# Generated by Django 5.1.4 on 2025-01-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0008_seller_createon_seller_lastlogin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seller",
            old_name="userName",
            new_name="name",
        ),
    ]
