# Generated by Django 5.1.4 on 2025-01-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0009_rename_username_seller_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="city",
            field=models.CharField(default="city", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seller",
            name="district",
            field=models.CharField(default="district", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seller",
            name="pincode",
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seller",
            name="state",
            field=models.CharField(default="state", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="seller",
            name="contact",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
