# Generated by Django 5.1.4 on 2025-01-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_seller_city_seller_district_seller_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='sessionID',
            field=models.CharField(default=None, max_length=36),
            preserve_default=False,
        ),
    ]
