# Generated by Django 5.1.4 on 2025-01-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_seller_dialcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(default=None, upload_to='seller/'),
            preserve_default=False,
        ),
    ]
