# Generated by Django 5.1.4 on 2025-01-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_seller_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seller/'),
        ),
    ]
