# Generated by Django 5.1.4 on 2025-04-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0020_alter_seller_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
