# Generated by Django 5.1.4 on 2025-04-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0021_alter_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='companyName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gstin',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
