# Generated by Django 5.1.4 on 2025-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0022_alter_seller_companyname_alter_seller_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='companyName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gstin',
            field=models.CharField(max_length=15),
        ),
    ]
