# Generated by Django 5.1.4 on 2025-01-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("seller", "0005_delete_general_seller_sellerid"),
    ]

    operations = [
        migrations.CreateModel(
            name="countryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("dialCode", models.CharField(max_length=5)),
                ("image", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                ("productName", models.CharField(max_length=250)),
                ("productID", models.IntegerField(primary_key=True, serialize=False)),
                ("price", models.IntegerField()),
                ("stock", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="seller.seller"
                    ),
                ),
            ],
        ),
    ]
