# Generated by Django 5.1.4 on 2025-01-07 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="productID",
        ),
        migrations.AddField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="productCategory",
            field=models.CharField(choices=[("t", "toys")], default="t", max_length=1),
        ),
        migrations.CreateModel(
            name="orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("orderDate", models.DateTimeField(auto_now_add=True)),
                (
                    "orderStatus",
                    models.CharField(
                        choices=[
                            ("p", "pending"),
                            ("s", "shipped"),
                            ("d", "delivered"),
                            ("c", "canceled"),
                        ],
                        default="p",
                        max_length=1,
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
        ),
    ]
