# Generated by Django 5.1.4 on 2025-01-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_product_productid_product_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="countryCode",
        ),
    ]
