# Generated by Django 5.1.4 on 2025-01-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_orders_totalitems"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="orderDate",
            new_name="orderOn",
        ),
        migrations.RenameField(
            model_name="orders",
            old_name="orderStatus",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="productCategory",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="productName",
            new_name="name",
        ),
    ]
