# Generated by Django 5.1.4 on 2025-01-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_orderdate_orders_orderon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('t', 'toys'), ('e', 'electronics'), ('f', 'fashion'), ('b', 'beauty_and_personal_care'), ('h', 'home_and_furniture'), ('s', 'sports_and_outdoors'), ('p', 'books_and_stationery'), ('f_&_b', 'food_and_beverages'), ('h_&_m', 'health_and_medical'), ('a_&_t', 'automotive_and_tools'), ('p_s', 'pet_supplies'), ('o_p', 'office_products'), ('a_c', 'arts_and_crafts'), ('b_k', 'baby_and_kids'), ('l_d', 'luxury_and_designer'), ('b_m_m', 'books_music_and_movies'), ('s_p', 'seasonal_products'), ('t_l', 'travel_and_luggage'), ('d_p', 'digital_products'), ('g_s', 'gifts_and_special_occasion'), ('s_e', 'sustainability_and_eco_friendly')], default='t', max_length=5),
        ),
    ]
