# Generated by Django 5.1.4 on 2025-05-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
