# Generated by Django 5.1.4 on 2025-05-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='totalItems',
        ),
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.JSONField(blank='True', default='list'),
        ),
    ]
