# Generated by Django 5.1.4 on 2025-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_orders_totalitems_alter_orders_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default=0, max_length=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='paymentMethod',
            field=models.CharField(choices=[('p', 'Pay on Delivery'), ('c', 'Credit/Debit Card'), ('u', 'UPI')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipment',
            field=models.CharField(choices=[('s', 'Standart'), ('e', 'Express')], default='s', max_length=1),
        ),
    ]
