# Generated by Django 5.1.4 on 2025-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_orders_quantity_orders_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderID',
            field=models.CharField(default='MVM-0-0000', max_length=20),
            preserve_default=False,
        ),
    ]
