# Generated by Django 5.1.4 on 2025-06-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orders_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderID',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('s', 'Shipped'), ('d', 'Delivered'), ('c', 'Canceled')], default='p', max_length=1),
        ),
    ]
