# Generated by Django 5.1.4 on 2025-06-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('p', 'Placed'), ('pr', 'Processing'), ('s', 'Shipped'), ('d', 'Delivered'), ('c', 'Canceled')], default='p', max_length=2),
        ),
    ]
