# Generated by Django 5.1.4 on 2025-01-07 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0001_initial"),
        ("core", "0002_remove_product_productid_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="contact",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="order",
            field=models.ForeignKey(
                default=20,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.orders",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
        ),
    ]
