# Generated by Django 5.1.4 on 2025-01-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0003_alter_users_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="contact",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
