# Generated by Django 5.1.4 on 2025-01-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0007_users_createon_users_lastlogin"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="city",
            field=models.CharField(default="city", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="district",
            field=models.CharField(default="district", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="pincode",
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="state",
            field=models.CharField(default="state", max_length=50),
            preserve_default=False,
        ),
    ]
