# Generated by Django 5.1.4 on 2025-01-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0008_users_city_users_district_users_pincode_users_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sessionID',
            field=models.CharField(default=None, max_length=36),
            preserve_default=False,
        ),
    ]
