# Generated by Django 5.1.4 on 2025-01-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0013_users_sessionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='sessionID',
        ),
    ]
