# Generated by Django 5.1.4 on 2025-01-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0015_users_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default=None, upload_to='consumer/'),
            preserve_default=False,
        ),
    ]
