# Generated by Django 5.1.4 on 2025-01-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0017_alter_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
