# Generated by Django 5.1.4 on 2025-04-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0019_cart_quantity_cart_user_alter_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
