# Generated by Django 5.1.4 on 2025-04-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0021_remove_cart_quantity_alter_cart_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
