# Generated by Django 5.1.4 on 2025-04-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0022_alter_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
