# Generated by Django 5.1.4 on 2025-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0025_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
