# Generated by Django 5.1.4 on 2025-05-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0026_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
