# Generated by Django 5.1.4 on 2025-05-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0027_alter_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='city',
        ),
        migrations.RemoveField(
            model_name='users',
            name='district',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='users',
            name='state',
        ),
        migrations.AddField(
            model_name='users',
            name='addresses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
