# Generated by Django 5.1.4 on 2025-05-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0028_remove_users_city_remove_users_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='addresses',
            new_name='address',
        ),
    ]
