# Generated by Django 5.1.4 on 2025-05-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0029_rename_addresses_users_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipment',
            field=models.CharField(choices=[('s', 'Standart'), ('e', 'Express')], default='s', max_length=1),
        ),
    ]
