# Generated by Django 5.1.4 on 2025-05-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0030_cart_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipment',
        ),
    ]
