# Generated by Django 5.1.4 on 2025-05-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0031_remove_cart_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
