# Generated by Django 5.1.4 on 2025-06-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0032_alter_users_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
