# Generated by Django 5.1.4 on 2025-06-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0033_alter_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\DELL\\Desktop\\projects and learings\\temp\\e-com\\e-com\\media/consumer/images'),
        ),
    ]
